config/routes.rb
Rails.application.routes.draw do
	root "gossips#index"
	get '/contact', to: 'static_pages#contact', as: 'contact'
	get '/team', to: 'static_pages#team', as: 'team'
	resources :gossips
	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	resources :cities
	resources :likes, only: [:create, :destroy]
	resources :comments, only: [:create, :destroy, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :potins
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :potin
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :potin
end

app/models/potin.rb
class Potin < ApplicationRecord
	validates :title,
		presence: true
	validates :content,
		presence: true
	belongs_to :user
	belongs_to :city
	has_many :likes
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
	validates :first_name, presence: true
	validates :last_name, presence: true
	has_many :potins
	has_secure_password
	has_many :comments
	has_many :likes
	belongs_to :city 

	validates :password,
		presence: true,
		length: {minimum: 6}

	validates :email,
		uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @all_cities = City.all
  end

  def show
    @selected_city = City.find_by(id: params[:id])
    @all_likes = Like.all
    @selected_potins = Potin.where(city_id: @selected_city.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        c = Comment.create(content: params[:content], user_id: session[:user_id], potin_id: params[:potin])
        redirect_to gossip_path(params[:potin])
    end

    def edit
        @selected_comment = Comment.find(params[:id])
    end

    def destroy
        @selected_comment = Comment.find(params[:id])
        potin = @selected_comment.potin_id
		@selected_comment.destroy
        redirect_to gossip_path(potin)
    end

    def update
        @selected_comment = Comment.find(params[:id])
		@selected_comment.update(content: params[:content])
		redirect_to gossip_path(@selected_comment.potin_id)
    end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	def index
		@all_gossips = Potin.all
		@all_likes = Like.all
	end
	def show
		@selected_gossip = Potin.find(params[:id])
		@all_likes = Like.all
		@selected_comments = nil
		@selected_comments = Comment.where(potin: @selected_gossip)
	end
	def create
		p = Potin.create(title: params[:title], content: params[:content], user_id: session[:user_id], city_id: User.find_by(id: session[:user_id]).city.id)
		if p.save
			flash[:success] = "Potin bien créé !"
			redirect_to gossips_path
		else
			render :new
		end
	end
	def edit
		@selected_gossip = Potin.find(params[:id])
	end
	def update
		@selected_gossip = Potin.find(params[:id])
		@selected_gossip.update(title: params[:title], content: params[:content])
		redirect_to gossips_path
	end
	def destroy
		@selected_gossip = Potin.find(params[:id])
		@selected_gossip.destroy
		redirect_to gossips_path
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		like = Like.create(potin_id: params[:id], user_id: session[:user_id])
		redirect_to request.referrer
	end
	def destroy
		selected_like = Like.find_by(potin_id: params[:id].to_i, user_id: session[:user_id])
		selected_like.destroy
		redirect_to request.referrer
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path

    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
   session.delete(:user_id)
   redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def team
	end
	def contact
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@all_users = User.all
	end
	def show
		@selected_user = User.find(params[:id])
		@selected_city = User.find(params[:id]).city.name
	end

	def create
		u = User.create(last_name: params[:last_name], first_name: params[:first_name], email: params[:email], age: params[:age], password: params[:password], description: params[:description], city_id: params[:city].to_i)
		redirect_to root_path
	end

	def new
		@all_cities = City.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/index.html.erb
<h1 class="page-title">Les villes</h1>

<%
@all_cities.each do |city|
%>

<article>
	<h3 class="user-name"><%= city.name %> </h3>
	<%= link_to "Lien vers la ville", city_path(city.id), class:"article-btn" %>
</article>

<% end %>

app/views/cities/show.html.erb
<h1 class="page-title"> <%= @selected_city.name %> </h1>

<% @selected_potins.each do |potin| %>
<article>
	<h3 class="user-name"><%= potin.user.first_name %> <%= potin.user.last_name %></h3>
	<h4 class="desc-title"><%= potin.title %></h4>
	<p class="desc"><%= potin.content %></p>
	<p class="desc">Nombre de commmentaires : <%= potin.comments.count %></p>
	<p class="desc">Nombre de likes : <%= potin.likes.count %></p>
	<%= link_to "Lien vers le potin", gossip_path(potin.id), class:"article-btn" %>
	<% unless current_user

		else
			is_liked = 0
			@all_likes.each do |like|
				if like.user_id == session[:user_id] && like.potin_id == potin.id
				%>
				<%= form_tag(like_path(potin.id), method: 'delete', class: 'like-form') do %>
				<%= submit_tag('Unlike', :class=>'article-btn like-btn') %>
				<% end %>
				<% is_liked = 1
				end
			end %>
			<% if is_liked == 0 %>
			<%= form_tag(likes_path, method: 'post', class: 'like-form') do %>
			<%= hidden_field_tag('id', potin.id) %>
			<%= submit_tag('Like', :class=>'article-btn like-btn') %>
			<% end %>
			<% end
		end %> 
</article>

<% end %>

app/views/comments/edit.html.erb
<h1 class="page-title">Editer le commentaire</h1>

<%= form_tag url_for(action: 'update'), method: 'patch' do%>
<%= label_tag('content', 'Votre commentaire :', :class=>'label-tag form-item tag-row-1') %>
<%= text_field_tag('content', @selected_comment.content, :class=>'field-tag form-item tag-row-1')%>
<%= submit_tag('Éditer', :class=>'submit-tag form-item article-btn')%>
<% end %>

app/views/gossips/edit.html.erb
<h1 class="page-title">Editer le potin</h1>

<%= form_tag url_for(action: 'update'), method: 'patch' do%>
<%= label_tag('title', 'Titre', :class=>'label-tag form-item tag-row-1') %>
<%= text_field_tag('title', @selected_gossip.title, :class=>'field-tag form-item tag-row-1')%>
<%= label_tag('content', 'Potin', :class=>'label-tag form-item tag-row-2')%>
<%= text_area_tag('content', @selected_gossip.content, :class=>'field-tag text-tag form-item tag-row-2')%>
<%= submit_tag('Éditer', :class=>'submit-tag form-item article-btn')%>
<% end %>

app/views/gossips/index.html.erb
<div class="title-container">
<h1 class="page-title">Gossips</h1>
<%
unless current_user
else
%>
<%= link_to "Nouveau potin", new_gossip_path, class:"article-btn" %>
<% end %>
</div>
<%
@all_gossips.each do |potin|
%>
<article>
	<h3 class="user-name"><%= potin.user.first_name %> <%= potin.user.last_name %></h3>
	<h4 class="desc-title"><%= potin.title %></h4>
	<p class="desc"><%= potin.content %></p>
	<p class="desc">Nombre de commmentaires : <%= potin.comments.count %></p>
	<p class="desc">Nombre de likes : <%= potin.likes.count %></p>
	<%= link_to "Lien vers le potin", gossip_path(potin.id), class:"article-btn" %>
	<% unless current_user

		else
			is_liked = 0
			@all_likes.each do |like|
				if like.user_id == session[:user_id] && like.potin_id == potin.id
				%>
				<%= form_tag(like_path(potin.id), method: 'delete', class: 'like-form') do %>
				<%= submit_tag('Unlike', :class=>'article-btn like-btn') %>
				<% end %>
				<% is_liked = 1
				end
			end %>
			<% if is_liked == 0 %>
			<%= form_tag(likes_path, method: 'post', class: 'like-form') do %>
			<%= hidden_field_tag('id', potin.id) %>
			<%= submit_tag('Like', :class=>'article-btn like-btn') %>
			<% end %>
			<% end
		end %> 
</article>
<%
end
%>

app/views/gossips/new.html.erb
<h1 class="page-title">Créer un potin</h1>

<%= form_tag(gossips_path, method: 'post') do%>
<%= label_tag('title', 'Titre', :class=>'label-tag form-item tag-row-1') %>
<%= text_field_tag('title', nil, :class=>'field-tag form-item tag-row-1')%>
<%= label_tag('content', 'Potin', :class=>'label-tag form-item tag-row-2')%>
<%= text_area_tag('content', nil, :class=>'field-tag text-tag form-item tag-row-2')%>
<%= submit_tag('Créer', :class=>'submit-tag form-item article-btn')%>
<% end %>

app/views/gossips/show.html.erb
<h1 class="page-title">Potin</h1>

<div class="show-container">
	<h3 class="user-name"><%= @selected_gossip.user.first_name %> <%= @selected_gossip.user.last_name %></h3>
	<p class="desc">Nombre de likes : <%= @selected_gossip.likes.count %></p>
	<h4 class="desc-title"><%= @selected_gossip.title %></h4>
	<p class="show-description"><%= @selected_gossip.content %></p>
</div>

<% unless current_user

		else
			is_liked = 0
			@all_likes.each do |like|
				if like.user_id == session[:user_id] && like.potin_id == @selected_gossip.id
				%>
				<%= form_tag(like_path(@selected_gossip.id), method: 'delete', class: 'like-form') do %>
				<%= submit_tag('Unlike', :class=>'article-btn like-btn') %>
				<% end %>
				<% is_liked = 1
				end
			end %>
			<% if is_liked == 0 %>
			<%= form_tag(likes_path, method: 'post', class: 'like-form') do %>
			<%= hidden_field_tag('id', @selected_gossip.id) %>
			<%= submit_tag('Like', :class=>'article-btn like-btn') %>
			<% end %>
			<% end
		end %> 

<% unless current_user
else %>

	<% if session[:user_id] == @selected_gossip.user_id
	%>
<div class="show-edit">
<%= link_to 'Editer', edit_gossip_path(@selected_gossip.id), class:'article-btn'%>
<%= link_to 'Supprimer', gossip_path(@selected_gossip.id), method: 'delete', class:'article-btn btn-grey'%>
</div>
<% end %>
<% end %>


<% unless current_user
else %>

<%= form_tag(comments_path, method: 'post') do %>
	<%= hidden_field_tag('potin', @selected_gossip.id) %>
	<%= label_tag('content', 'Nouveau commentaire', :class=>'label-tag form-item') %>
	<%= text_field_tag('content', nil, :class=>'field-tag form-item')%>
	<%= submit_tag('Poster', :class=>'submit-tag form-item article-btn')%>
	<% end %> 
	<% end %>

<% @selected_comments.each do |comment| %>
	<article> 
		<h3 class="user-name"><%= comment.user.first_name %> <%= comment.user.last_name %></h3>
		<h4 class="desc-title">Commentaire</h4>
		<p class="desc"><%= comment.content %></p>

		<% unless current_user
		else %>

		<% if session[:user_id] == comment.user_id
		%>
		<div class="show-edit">
			<%= link_to 'Editer', edit_comment_path(comment.id), class:'article-btn'%>
			<%= link_to 'Supprimer', comment_path(comment.id), method: 'delete', class:'article-btn btn-grey'%>
			</div>
		<% end %>
		<% end %>
	</article>

<% end %> 

app/views/static_pages/contact.html.erb
<h1 class="page-title">Contact</h1>

<h3 class="user-name">Non</h3>

app/views/static_pages/team.html.erb
<h1 class="page-title">L'équipe</h1>

<%
admins = User.where("is_admin = '1'")

admins.each do |user_admin|
%>
<article>
	<h3 class="user-name"><%= user_admin.first_name %> <%= user_admin.last_name %></h3>
	<h4 class="desc-title">Description :</h4>
	<p class="desc"><%= user_admin.description %></p>
	<%=link_to "Lien vers le profil", user_path(user_admin.id), class:"article-btn" %>
</article>
<%
end
%>

app/views/users/index.html.erb
<h1 class="page-title">Membres</h1>

<%
@all_users.each do |user|
%>
<article>
	<h3 class="user-name"><%= user.first_name %> <%= user.last_name %></h3>
	<h4 class="desc-title">Description :</h4>
	<p class="desc"><%= user.description %></p>
	<%=link_to "Lien vers le profil", user_path(user.id), class:"article-btn" %>
</article>
<%
end
%>

app/views/users/new.html.erb
<h1 class="page-title">Inscription</h1>

<%= form_tag(users_path, :methode=>:post) do%>
<%= label_tag('last_name', 'Nom', :class=>'label-tag form-item tag-row-1') %>
<%= text_field_tag('last_name', nil, :class=>'field-tag form-item tag-row-1')%>

<%= label_tag('first_name', 'Prénom', :class=>'label-tag form-item tag-row-1') %>
<%= text_field_tag('first_name', nil, :class=>'field-tag form-item tag-row-1')%>

<%= label_tag('age', 'Âge', :class=>'label-tag form-item tag-row-1') %>
<%= text_field_tag('age', nil, :class=>'field-tag form-item tag-row-1')%>

<%= label_tag('description', 'Description', :class=>'label-tag form-item tag-row-1') %>
<%= text_field_tag('description', nil, :class=>'field-tag form-item tag-row-1')%>

<%= label_tag('city', 'Votre ville', :class=>'label-tag form-item tag-row-1') %>
<select class="field-tag form-item select-tag" name="city">
<% @all_cities.each do |city| %>
<option value="<%= city.id %>"><%= city.name %></option>
<% end %>
</select>

<%= label_tag('email', 'Votre adresse email', :class=>'label-tag form-item tag-row-1') %>
<%= text_field_tag('email', nil, :class=>'field-tag form-item tag-row-1')%>

<%= label_tag('password', 'Votre mot de passe', :class=>'label-tag form-item tag-row-2')%>
<%= text_field_tag('password', nil, :class=>'field-tag form-item tag-row-2')%>

<%= submit_tag('Inscription', :class=>'submit-tag form-item article-btn')%>
<% end %>

app/views/users/show.html.erb
<h1 class="page-title">Membre</h1>

<div class="show-container">
	<h3 class="user-name"><%= @selected_user.first_name %> <%= @selected_user.last_name %></h3>
	<h4 class="desc-title">Age :</h4>
	<p class="show-description"><%= @selected_user.age %></p>
	<h4 class="desc-title">Ville :</h4>
	<p class="show-description"><%= @selected_city %></p>
	<h4 class="desc-title">Description :</h4>
	<p class="show-description"><%= @selected_user.description %></p>
</div>