config/routes.rb
Rails.application.routes.draw do
	root "gossips#index"
	get '/contact', to: 'static_pages#contact', as: 'contact'
	get '/team', to: 'static_pages#team', as: 'team'
	resources :gossips
	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	resources :cities
	resources :likes, only: [:create, :destroy]
	resources :comments, only: [:create, :destroy, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :potins
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :potin
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :potin
end

app/models/potin.rb
class Potin < ApplicationRecord
	validates :title,
		presence: true
	validates :content,
		presence: true
	belongs_to :user
	belongs_to :city
	has_many :likes
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
	validates :first_name, presence: true
	validates :last_name, presence: true
	has_many :potins
	has_secure_password
	has_many :comments
	has_many :likes
	belongs_to :city 

	validates :password,
		presence: true,
		length: {minimum: 6}

	validates :email,
		uniqueness: true
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @all_cities = City.all
  end

  def show
    @selected_city = City.find_by(id: params[:id])
    @all_likes = Like.all
    @selected_potins = Potin.where(city_id: @selected_city.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        c = Comment.create(content: params[:content], user_id: session[:user_id], potin_id: params[:potin])
        redirect_to gossip_path(params[:potin])
    end

    def edit
        @selected_comment = Comment.find(params[:id])
    end

    def destroy
        @selected_comment = Comment.find(params[:id])
        potin = @selected_comment.potin_id
		@selected_comment.destroy
        redirect_to gossip_path(potin)
    end

    def update
        @selected_comment = Comment.find(params[:id])
		@selected_comment.update(content: params[:content])
		redirect_to gossip_path(@selected_comment.potin_id)
    end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	def index
		@all_gossips = Potin.all
		@all_likes = Like.all
	end
	def show
		@selected_gossip = Potin.find(params[:id])
		@all_likes = Like.all
		@selected_comments = nil
		@selected_comments = Comment.where(potin: @selected_gossip)
	end
	def create
		p = Potin.create(title: params[:title], content: params[:content], user_id: session[:user_id], city_id: User.find_by(id: session[:user_id]).city.id)
		if p.save
			flash[:success] = "Potin bien créé !"
			redirect_to gossips_path
		else
			render :new
		end
	end
	def edit
		@selected_gossip = Potin.find(params[:id])
	end
	def update
		@selected_gossip = Potin.find(params[:id])
		@selected_gossip.update(title: params[:title], content: params[:content])
		redirect_to gossips_path
	end
	def destroy
		@selected_gossip = Potin.find(params[:id])
		@selected_gossip.destroy
		redirect_to gossips_path
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		like = Like.create(potin_id: params[:id], user_id: session[:user_id])
		redirect_to request.referrer
	end
	def destroy
		selected_like = Like.find_by(potin_id: params[:id].to_i, user_id: session[:user_id])
		selected_like.destroy
		redirect_to request.referrer
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path

    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
   session.delete(:user_id)
   redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@all_users = User.all
	end
	def show
		@selected_user = User.find(params[:id])
		@selected_city = User.find(params[:id]).city.name
	end

	def create
		u = User.create(last_name: params[:last_name], first_name: params[:first_name], email: params[:email], age: params[:age], password: params[:password], description: params[:description], city_id: params[:city].to_i)
		redirect_to root_path
	end

	def new
		@all_cities = City.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <header>
        <nav>
          <a href="/" class="nav-title nav-item">Gossip</a>
          <ul class="nav-menu">
            <li><a href="<%= team_path %>" class="nav-link nav-item">L'équipe</a></li>
            <li><a href="<%= users_path %>" class="nav-link nav-item">Membres</a></li>
            <li><a href="<%= cities_path %>" class="nav-link nav-item">Villes</a></li>
            <li><a href="<%= contact_path %>" class="nav-link nav-item">Contact</a></li>
            <% unless current_user %>
              <li><a href="<%= new_user_path %>" class="nav-link nav-item">S'inscrire</a></li>
              <li><a href="<%= new_session_path %>" class="nav-link nav-item">Se connecter</a></li>
            <% else %>
              <li><%= link_to "Se déconnecter", session_path(current_user), method: 'delete', class:"nav-link nav-item" %></li>
            <% end %>
          </ul>
        </nav>
      </header>
      <main>
        <%= yield %>
      </main>
      <footer>
        <p>Made by THP Rennes 7</p>
      </footer>
    </div>
  </body>
</html>